### ISSUE TITLE
suggestion: add background triggers

### ISSUE THREAD

**Issue by rubiidev18alt** [Alphalaneous/Level-Info-Backgrounds#4]
what this does: basically uses bg triggers from the level, durations, where in the level and all. 
required triggers to work: 
color triggers, 
pulse, 
shaders, 
bg and g changer triggers,
and bg speed, it would be a fun addition. additionally, you can disable these triggers in the config

**Comment by Alphalaneous** [comment]
As I have mentioned in two other similar suggestions. This will cause lag when going between levels. I have to parse the whole level which is not a good thing for high object levels.

**Comment by rubiidev18alt** [comment]
> As I have mentioned in two other similar suggestions. This will cause lag when going between levels. I have to parse the whole level which is not a good thing for high object levels.

ay, you can just do a few of the triggers at the start and loop those, doesn't parse that much!
